version: '3'

services:
  volume_configurer:
    # https://medium.com/ncr-edinburgh/docker-tips-tricks-516b9ba41aa2
    #chmod -R 777 /shared/;
    image: busybox
    volumes:
      - shared:/shared:z
    command: ["/bin/sh", "-c", "
      mkdir -p /shared/sync;
      chmod -R 777 /shared/sync;
      echo STARTED > /shared/sync/volumesetter && chmod a+r /shared/sync/volumesetter"]
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    env_file:
     - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data1:/var/lib/postgresql/data1:z
  plumber:
    build:
      context: ./
      dockerfile: ./rplumber/Dockerfile
    container_name: rplumber
    command: /app/plumber.R
    #command: ["/bin/sh", "-c", "
    #  Rscript /app/plumber.R;
    #  Rscript /app/start_idbac.R"]
    restart: always
    env_file:
      - project.env
    ports:
      - 7002:8000
    #  - 7125:7125 #idbac
    volumes:
      - ./rplumber:/app:z
      - shared:/app/uploads:z
  web:
    build:
      context: ./
      dockerfile: ./mdb/Dockerfile
    container_name: django
    command: >
      gunicorn mdb.wsgi:application --bind 0.0.0.0:8000 --workers=4 --timeout 1000 --access-logfile -
    env_file:
      - project.env
    expose:
      - 8000
    depends_on:
      - db
      - plumber
    volumes:
      - ./mdb:/home/app/web/:z
      - staticfiles:/home/app/web/static/:z
      - shared:/uploads/:z
  nginx:
    container_name: nginx
    image: nginx #####:mainline-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d:z
      - staticfiles:/home/app/web/static/:z
     #- uploads:/home/app/web/media/uploads/:z
     #- ./mdb/media/uploads:/home/app/web/media/uploads:z
    depends_on:
      - web
      - db
      - plumber

volumes:
  postgres-data1:
  staticfiles:
  shared:
  #./mdb/media/uploads: #:/uploads
