version: '3'

services:
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data1:/var/lib/postgresql/data1:z
  plumber:
    build: ./rplumber/
    command: /app/plumber.R
    restart: always
    env_file:
      - project.env
    ports:
     - 7002:8000
    volumes:
     - ./rplumber:/app:z
  web:
    container_name: django
    build: maldidb/
    command: >
      gunicorn soMedia.wsgi:application --bind 0.0.0.0:8000 --workers=4 --timeout 1000
    env_file:
      - project.env
    expose:
      - 8000
    depends_on:
      - db
      - plumber
    volumes:
      - staticfiles:/home/app/web/static/:z
      - ./r01data:/home/app/r01data/:z
  nginx:
    container_name: nginx
    image: nginx #####:mainline-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d:z
      - staticfiles:/home/app/web/static/:z
    depends_on:
      - web
      - db
      - plumber

volumes:
  postgres-data1:
  staticfiles:
