version: '3'

services:
  volume_configurer:
    # https://medium.com/ncr-edinburgh/docker-tips-tricks-516b9ba41aa2
    # More:
    # https://github.com/docker/compose/issues/3270#issuecomment-537763768
    image: busybox
    volumes:
      - shared:/shared:z
      - static:/static:z
    command: ["/bin/sh", "-c", "
      mkdir -p /static;
      chmod -R 777 /static;
      mkdir -p /shared/sync;
      chmod -R 777 /shared/sync;
      echo STARTED > /shared/sync/volumesetter && chmod a+r /shared/sync/volumesetter"]
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    env_file:
     - project.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data1:/var/lib/postgresql/data1:z
  plumber:
    build:
      context: ./
      dockerfile: ./rplumber/Dockerfile
    container_name: rplumber
    command: /app/plumber.R
    #command: ["/bin/sh", "-c", "
    #  Rscript /app/plumber.R;
    #  Rscript /app/start_idbac.R"]
    restart: always
    env_file:
      - project.env
    ports:
      - "127.0.0.1:7002:8000"
    volumes:
      - ./rplumber:/app:z
      - shared:/app/uploads:z
  web:
    build:
      context: ./
      dockerfile: ./mdb/Dockerfile
    container_name: django
    command: >
      daphne mdb.asgi:application -b 0.0.0.0 -p 8000
    env_file:
      - project.env
    #~ expose:
    ports:
      - "127.0.0.1:8000:8000" # 8000
    depends_on:
      - db
      - plumber
    volumes:
      - ./mdb:/home/app/web/:z
      - static:/home/app/web/static/:z
      - shared:/uploads/:z
    environment:
      PYTHONUNBUFFERED: 1 # better printing
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d:z
      - static:/home/app/web/static/:z
    depends_on:
      - web
      - db
      - plumber

volumes:
  postgres-data1:
  static: 
  shared:
