# Generated by Django 3.1 on 2021-07-08 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('short_title', models.CharField(max_length=200)),
                ('long_title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('category', 'Category'), ('sub-category', 'Sub-category')], max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('content', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.docspage')),
            ],
        ),
    ]
