# Generated by Django 3.1 on 2021-07-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210708_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
