# Generated by Django 3.1 on 2021-07-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20210708_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='long_title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='short_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
