# Generated by Django 3.1 on 2021-07-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20210708_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
