# Generated by Django 3.1 on 2021-07-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20210709_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
