# Generated by Django 2.2.13 on 2020-09-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200901_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='testField',
            field=models.TextField(blank=True),
        ),
    ]
