# Generated by Django 2.2.13 on 2020-09-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_post_spectraid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cKingdom', models.TextField()),
                ('cPhylum', models.TextField()),
                ('cClass', models.TextField()),
                ('cOrder', models.TextField()),
                ('cGenus', models.TextField()),
                ('cSpecies', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='md',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='chat.Metadata'),
            preserve_default=False,
        ),
    ]
