# Generated by Django 2.2.13 on 2020-10-01 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20201001_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ignore',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='laser_attenuation',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='laser_shots',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='mass_error',
            field=models.DecimalField(blank=True, decimal_places=20, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='max_mass',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='min_mass',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='peak_matrix',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='spectrum_intensity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_delay',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='time_delta',
            field=models.DecimalField(blank=True, decimal_places=20, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='strain_id',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='md',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='chat.Metadata'),
        ),
        migrations.AlterField(
            model_name='post',
            name='spectrum_intensity_hash',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='spectrum_mass_hash',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='strain_id',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xml',
            name='xml_hash',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
