# Generated by Django 2.2.13 on 2020-10-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20201004_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='privacyLevel',
            field=models.CharField(choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2),
        ),
    ]
