# Generated by Django 2.2.13 on 2020-10-06 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0018_auto_20201004_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='spectra')),
                ('text', models.TextField(blank=True, max_length=2048)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('spectrum_mass_hash', models.TextField(blank=True)),
                ('spectrum_intensity_hash', models.TextField(blank=True)),
                ('xml_hash', models.TextField(blank=True)),
                ('strain_id', models.TextField(blank=True)),
                ('peak_matrix', models.TextField(blank=True)),
                ('spectrum_intensity', models.TextField(blank=True)),
                ('max_mass', models.IntegerField(blank=True)),
                ('min_mass', models.IntegerField(blank=True)),
                ('ignore', models.IntegerField(blank=True)),
                ('number', models.IntegerField(blank=True)),
                ('time_delay', models.IntegerField(blank=True)),
                ('time_delta', models.DecimalField(blank=True, decimal_places=20, max_digits=30)),
                ('calibration_constants', models.TextField(blank=True)),
                ('v1_tof_calibration', models.TextField(blank=True)),
                ('data_type', models.TextField(blank=True)),
                ('data_system', models.TextField(blank=True)),
                ('spectrometer_type', models.TextField(blank=True)),
                ('inlet', models.TextField(blank=True)),
                ('ionization_mode', models.TextField(blank=True)),
                ('acquisition_method', models.TextField(blank=True)),
                ('acquisition_date', models.TextField(blank=True)),
                ('acquisition_mode', models.TextField(blank=True)),
                ('tof_mode', models.TextField(blank=True)),
                ('acquisition_operator_mode', models.TextField(blank=True)),
                ('laser_attenuation', models.IntegerField(blank=True)),
                ('digitizer_type', models.TextField(blank=True)),
                ('flex_control_version', models.TextField(blank=True)),
                ('cId', models.TextField(blank=True)),
                ('instrument', models.TextField(blank=True)),
                ('instrument_id', models.TextField(blank=True)),
                ('instrument_type', models.TextField(blank=True)),
                ('mass_error', models.DecimalField(blank=True, decimal_places=20, max_digits=30)),
                ('laser_shots', models.IntegerField(blank=True)),
                ('patch', models.TextField(blank=True)),
                ('path', models.TextField(blank=True)),
                ('laser_repetition', models.TextField(blank=True)),
                ('spot', models.TextField(blank=True)),
                ('spectrum_type', models.TextField(blank=True)),
                ('target_count', models.TextField(blank=True)),
                ('target_id_string', models.TextField(blank=True)),
                ('target_serial_number', models.TextField(blank=True)),
                ('target_type_number', models.TextField(blank=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='comment',
            name='spectra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chat.Spectra'),
            preserve_default=False,
        ),
    ]
