# Generated by Django 2.2.13 on 2020-10-06 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0021_auto_20201006_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectra',
            name='user',
        ),
        migrations.AddField(
            model_name='library',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spectra',
            name='uploadedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='privacyLevel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chat.PrivacyLevel'),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='md',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_metadata', to='chat.Metadata'),
        ),
    ]
