# Generated by Django 2.2.13 on 2020-12-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_collapsedspectra_generated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='privacy_level',
            field=models.CharField(choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2),
        ),
    ]
