# Generated by Django 2.2.13 on 2020-12-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_auto_20201222_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectra',
            name='strain_id',
            field=models.ForeignKey(blank=True, db_column='strain_id', on_delete=django.db.models.deletion.CASCADE, to='chat.Metadata'),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='xml_hash',
            field=models.ForeignKey(db_column='xml_hash', on_delete=django.db.models.deletion.CASCADE, to='chat.XML'),
        ),
    ]
