# Generated by Django 2.2.13 on 2021-01-09 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0052_searchspectracosinescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchspectra',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
