# Generated by Django 2.2.13 on 2020-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_labgroup'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lab_group',
            field=models.ManyToManyField(blank=True, to='chat.LabGroup'),
        ),
    ]
