# Generated by Django 3.1 on 2021-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='task_description',
            field=models.CharField(blank=True, choices=[('idbac_sql', 'Insert IDBac SQLite data to database'), ('spectra', 'Add spectra files to database'), ('preprocess', 'Preprocess spectra'), ('collapse', 'Collapse replicates'), ('cos_search', 'Cosine score search'), ('metadata', 'Add metadata')], max_length=255, null=True),
        ),
    ]
