# Generated by Django 3.1 on 2021-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_userfile_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='spectra',
        ),
        migrations.AddField(
            model_name='userfile',
            name='extension',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
