# Generated by Django 3.1 on 2021-08-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_auto_20210809_1158'),
        ('files', '0006_auto_20210809_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.library'),
        ),
    ]
