# Generated by Django 3.1 on 2021-08-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_library_created_date'),
        ('files', '0009_auto_20210816_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.library'),
        ),
        migrations.AlterUniqueTogether(
            name='userfile',
            unique_together={('file', 'library')},
        ),
    ]
