# Generated by Django 3.1 on 2021-08-17 01:05

import django.core.validators
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20210816_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(storage=files.models.OverwriteStorage(), upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mzml', 'mzxml', 'fid', 'csv'])]),
        ),
    ]
