# Generated by Django 3.1 on 2021-06-21 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncbitaxonomy.txnode')),
            ],
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
