# Generated by Django 3.1 on 2021-06-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0002_auto_20210621_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='txnode',
            name='txid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='txnode',
            unique_together={('name', 'txid')},
        ),
    ]
