# Generated by Django 3.1 on 2021-06-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0004_auto_20210622_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='txnode',
            name='txtype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
