# Generated by Django 3.1 on 2021-06-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0005_txnode_txtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='txnode',
            name='nodetype',
            field=models.CharField(choices=[('s', 'scientific name'), ('t', 'type material')], default='s', max_length=1),
        ),
    ]
