# Generated by Django 3.1 on 2021-06-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0006_txnode_nodetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='txnode',
            name='parentid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
