# Generated by Django 3.1 on 2021-06-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0007_txnode_parentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txnode',
            name='parent',
        ),
    ]
