# Generated by Django 3.1 on 2021-07-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0008_remove_txnode_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txnode',
            name='nodetype',
            field=models.CharField(choices=[('s', 'scientific name'), ('t', 'type material'), ('y', 'synonym')], default='s', max_length=1),
        ),
    ]
