# Generated by Django 3.1 on 2021-07-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0009_auto_20210704_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='txnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ncbitaxonomy.txnode'),
        ),
    ]
