# Generated by Django 3.1 on 2021-07-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0011_auto_20210705_1437'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='txnode',
            index=models.Index(fields=['name'], name='ncbitaxonom_name_0eac5a_idx'),
        ),
    ]
