# Generated by Django 3.1 on 2021-07-05 22:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncbitaxonomy', '0012_auto_20210705_1752'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='txnode',
            name='ncbitaxonom_name_0eac5a_idx',
        ),
        migrations.AddField(
            model_name='txnode',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='txnode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ncbitaxonom_search__480c4e_gin'),
        ),
    ]
