# Generated by Django 3.1 on 2021-05-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collapsedspectra',
            name='collapsed_spectra',
        ),
        migrations.RemoveField(
            model_name='collapsedspectra',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='collapsedspectra',
            name='lab_name',
        ),
        migrations.RemoveField(
            model_name='collapsedspectra',
            name='library',
        ),
        migrations.RemoveField(
            model_name='collapsedspectra',
            name='strain_id',
        ),
        migrations.RemoveField(
            model_name='collapsedspectra',
            name='xml_hash',
        ),
        migrations.RemoveField(
            model_name='searchspectra',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='searchspectra',
            name='lab_name',
        ),
        migrations.RemoveField(
            model_name='searchspectra',
            name='library',
        ),
        migrations.RemoveField(
            model_name='searchspectra',
            name='strain_id',
        ),
        migrations.RemoveField(
            model_name='searchspectra',
            name='xml_hash',
        ),
        migrations.RemoveField(
            model_name='spectra',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='spectra',
            name='lab_name',
        ),
        migrations.RemoveField(
            model_name='spectra',
            name='library',
        ),
        migrations.RemoveField(
            model_name='spectra',
            name='strain_id',
        ),
        migrations.RemoveField(
            model_name='spectra',
            name='xml_hash',
        ),
    ]
