# Generated by Django 3.1 on 2021-05-02 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20210502_1907'),
        ('spectra', '0001_initial'),
        ('chat', '0003_auto_20210502_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collapsedcosinescore',
            name='spectra1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra1', to='spectra.collapsedspectra'),
        ),
        migrations.AlterField(
            model_name='collapsedcosinescore',
            name='spectra2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra2', to='spectra.collapsedspectra'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='spectra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spectra.spectra'),
        ),
        migrations.AlterField(
            model_name='searchspectracosinescore',
            name='spectra1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_spectra1', to='spectra.searchspectra'),
        ),
        migrations.AlterField(
            model_name='searchspectracosinescore',
            name='spectra2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_spectra2', to='spectra.spectra'),
        ),
        migrations.AlterField(
            model_name='spectracosinescore',
            name='spectra1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra1', to='spectra.spectra'),
        ),
        migrations.AlterField(
            model_name='spectracosinescore',
            name='spectra2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra2', to='spectra.spectra'),
        ),
        migrations.DeleteModel(
            name='CollapsedSpectra',
        ),
        migrations.DeleteModel(
            name='SearchSpectra',
        ),
        migrations.DeleteModel(
            name='Spectra',
        ),
    ]
