# Generated by Django 3.1 on 2021-05-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210502_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchspectracosinescore',
            name='spectra1',
        ),
        migrations.RemoveField(
            model_name='searchspectracosinescore',
            name='spectra2',
        ),
        migrations.RemoveField(
            model_name='spectracosinescore',
            name='spectra1',
        ),
        migrations.RemoveField(
            model_name='spectracosinescore',
            name='spectra2',
        ),
        migrations.DeleteModel(
            name='CollapsedCosineScore',
        ),
        migrations.DeleteModel(
            name='SearchSpectraCosineScore',
        ),
        migrations.DeleteModel(
            name='SpectraCosineScore',
        ),
    ]
