# Generated by Django 3.1 on 2021-05-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210512_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='lab_name',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='lab_name',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='xml',
            old_name='lab_name',
            new_name='lab',
        ),
    ]
