# Generated by Django 3.1 on 2021-06-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_labgroup_user_default_lab'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('strain_id', 'library')},
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='lab',
        ),
    ]
