# Generated by Django 3.1 on 2021-06-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210630_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xml',
            name='lab',
        ),
        migrations.AddField(
            model_name='xml',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.library'),
        ),
    ]
