# Generated by Django 3.1 on 2021-06-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210630_2309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='xml',
            unique_together={('xml_hash', 'library')},
        ),
    ]
