# Generated by Django 3.1 on 2021-07-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20210630_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='cFamily',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
