# Generated by Django 3.1 on 2021-07-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_metadata_cfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='cSubspecies',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
