# Generated by Django 3.1 on 2021-07-11 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_metadata_csubspecies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.labgroup'),
        ),
    ]
