# Generated by Django 3.1 on 2021-07-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20210711_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='dna_16s',
            field=models.TextField(blank=True),
        ),
    ]
