# Generated by Django 3.1 on 2021-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20210711_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labgroup',
            name='user_default_lab',
        ),
        migrations.AddField(
            model_name='labgroup',
            name='lab_type',
            field=models.CharField(choices=[('user-uploads', 'User uploads lab'), ('user-default', 'User default lab'), ('other', 'Other lab')], default='other', max_length=20),
        ),
    ]
