# Generated by Django 3.1 on 2021-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210803_1904'),
        ('chat', '0019_auto_20210720_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='user_files',
            field=models.ManyToManyField(blank=True, to='files.UserFile'),
        ),
    ]
