# Generated by Django 3.1 on 2021-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_userfile_filename'),
        ('chat', '0021_auto_20210804_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='filenames',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='user_files', to='files.UserFile'),
        ),
    ]
