# Generated by Django 3.1 on 2021-08-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20210806_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='user_files',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='filenames',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='files',
        ),
    ]
