# Generated by Django 3.1 on 2021-08-15 23:10

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_auto_20210809_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
