# Generated by Django 2.2.13 on 2020-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intensities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='peaks',
            field=models.TextField(blank=True),
        ),
    ]
