# Generated by Django 2.2.13 on 2020-09-03 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_post_testfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spectraID',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
