# Generated by Django 2.2.13 on 2020-10-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200930_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='xml',
            name='instrument_metafile',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xml',
            name='xml',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
