# Generated by Django 2.2.13 on 2020-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20201001_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='cClass',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cGenus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cKingdom',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cOrder',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cPhylum',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cSpecies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cultivation_other',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cultivation_temp_celsius',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cultivation_time_days',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='dna_16s',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='dsm_cultivation_media',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='genbank_accession',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='maldi_matrix',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='ncbi_taxid',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='pi_firstname_lastname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='pi_orcid',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='strain_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='user_firstname_lastname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='user_orcid',
            field=models.TextField(blank=True),
        ),
    ]
