# Generated by Django 2.2.13 on 2020-10-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20201001_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intensities',
        ),
        migrations.RemoveField(
            model_name='post',
            name='peaks',
        ),
        migrations.RemoveField(
            model_name='post',
            name='spectraID',
        ),
        migrations.RemoveField(
            model_name='post',
            name='testField',
        ),
    ]
