# Generated by Django 2.2.13 on 2020-10-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20201001_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spectrum_intensity_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='spectrum_mass_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='strain_id',
            field=models.TextField(blank=True),
        ),
    ]
