# Generated by Django 2.2.13 on 2020-10-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20201001_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='strain_id',
            field=models.TextField(blank=True),
        ),
    ]
