# Generated by Django 2.2.13 on 2020-10-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20201004_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml',
            name='xml_hash',
            field=models.TextField(blank=True),
        ),
    ]
