# Generated by Django 2.2.13 on 2020-10-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20201006_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectra',
            name='md',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='chat.Metadata'),
            preserve_default=False,
        ),
    ]
