# Generated by Django 2.2.13 on 2020-10-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_spectra_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectra',
            name='md',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_species', to='chat.Metadata'),
        ),
    ]
