# Generated by Django 2.2.13 on 2020-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_auto_20201006_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='privacyLevel',
            new_name='privacy_level',
        ),
        migrations.RenameField(
            model_name='spectra',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='spectra',
            old_name='privacyLevel',
            new_name='privacy_level',
        ),
        migrations.AddField(
            model_name='library',
            name='quality_rating',
            field=models.CharField(choices=[('GO', 'Gold'), ('SI', 'Silver'), ('BR', 'Bronze')], default='BR', max_length=2),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='strain_id',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
