# Generated by Django 2.2.13 on 2020-10-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_labgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosineScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=6, max_digits=10)),
                ('spectra1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra1', to='chat.Spectra')),
                ('spectra2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra2', to='chat.Spectra')),
            ],
        ),
    ]
