# Generated by Django 2.2.13 on 2020-10-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_auto_20201022_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='collapsedspectra',
            name='spectrum_intensity_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collapsedspectra',
            name='spectrum_mass_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collapsedspectra',
            name='strain_id',
            field=models.ForeignKey(blank=True, db_column='strain_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.Metadata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collapsedspectra',
            name='xml_hash',
            field=models.ForeignKey(db_column='xml_hash', default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.XML'),
            preserve_default=False,
        ),
    ]
