# Generated by Django 2.2.13 on 2020-10-22 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_auto_20201022_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='collapsedspectra',
            name='generated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
