# Generated by Django 2.2.13 on 2020-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_auto_20201211_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectra',
            name='strain_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='xml_hash',
            field=models.TextField(blank=True),
        ),
    ]
