# Generated by Django 2.2.13 on 2020-12-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_auto_20201222_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collapsedspectra',
            name='privacy_level',
            field=models.CharField(choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='privacy_level',
            field=models.CharField(choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2),
        ),
    ]
