# Generated by Django 2.2.13 on 2021-01-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_auto_20201227_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collapsedspectra',
            old_name='spectrum_intensity',
            new_name='peak_intensity',
        ),
        migrations.RenameField(
            model_name='collapsedspectra',
            old_name='peak_matrix',
            new_name='peak_mass',
        ),
        migrations.RenameField(
            model_name='spectra',
            old_name='spectrum_intensity',
            new_name='peak_intensity',
        ),
        migrations.RenameField(
            model_name='spectra',
            old_name='peak_matrix',
            new_name='peak_mass',
        ),
        migrations.AddField(
            model_name='collapsedspectra',
            name='peak_snr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spectra',
            name='peak_snr',
            field=models.TextField(blank=True),
        ),
    ]
