# Generated by Django 2.2.13 on 2021-01-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_auto_20210101_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='collapsedspectra',
            name='lab_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chat.LabGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labgroup',
            name='lab_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='library',
            name='lab_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chat.LabGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spectra',
            name='lab_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chat.LabGroup'),
            preserve_default=False,
        ),
    ]
