# Generated by Django 2.2.13 on 2021-01-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_auto_20210102_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectra',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labgroup',
            name='lab_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locale',
            name='locale',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cClass',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cGenus',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cKingdom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cOrder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cPhylum',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cSpecies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='genbank_accession',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='ncbi_taxid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='pi_firstname_lastname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='pi_orcid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='strain_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='user_firstname_lastname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='user_orcid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='version',
            name='db_version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='version',
            name='idbac_version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='version',
            name='r_version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='xml',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='xml',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
