# Generated by Django 2.2.13 on 2021-01-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_auto_20210102_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collapsedspectra',
            old_name='lab_group',
            new_name='lab_name',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='lab_group',
            new_name='lab_name',
        ),
        migrations.RenameField(
            model_name='spectra',
            old_name='lab_group',
            new_name='lab_name',
        ),
    ]
