# Generated by Django 2.2.13 on 2021-01-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_auto_20210102_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='r_version',
            field=models.TextField(blank=True),
        ),
    ]
