# Generated by Django 2.2.13 on 2021-01-03 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0044_auto_20210103_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='labgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='lab_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
