# Generated by Django 2.2.13 on 2021-01-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0046_auto_20210105_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collapsedspectra',
            name='strain_id',
            field=models.ForeignKey(blank=True, db_column='strain_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Metadata'),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='strain_id',
            field=models.ForeignKey(blank=True, db_column='strain_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Metadata'),
        ),
    ]
