# Generated by Django 2.2.13 on 2021-01-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0047_auto_20210105_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collapsedspectra',
            name='xml_hash',
            field=models.ForeignKey(blank=True, db_column='xml_hash', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.XML'),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='xml_hash',
            field=models.ForeignKey(blank=True, db_column='xml_hash', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.XML'),
        ),
    ]
