# Generated by Django 2.2.13 on 2021-01-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0048_auto_20210105_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSpectra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_level', models.CharField(choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2)),
                ('peak_snr', models.TextField(blank=True)),
                ('spectrum_mass_hash', models.TextField(blank=True)),
                ('spectrum_intensity_hash', models.TextField(blank=True)),
                ('peak_mass', models.TextField(blank=True)),
                ('peak_intensity', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chat.LabGroup')),
                ('library', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Library')),
                ('strain_id', models.ForeignKey(blank=True, db_column='strain_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Metadata')),
                ('xml_hash', models.ForeignKey(blank=True, db_column='xml_hash', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.XML')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
