# Generated by Django 2.2.13 on 2021-01-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0050_auto_20210105_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collapsedspectra',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Library'),
        ),
        migrations.AlterField(
            model_name='searchspectra',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Library'),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Library'),
        ),
    ]
