# Generated by Django 2.2.13 on 2021-01-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0053_auto_20210109_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectra',
            name='ignore',
        ),
    ]
