# Generated by Django 2.2.13 on 2021-01-09 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0054_remove_spectra_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='xml',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xml',
            name='lab_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.LabGroup'),
            preserve_default=False,
        ),
    ]
