# Generated by Django 2.2.13 on 2021-01-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0055_auto_20210109_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collapsedspectra',
            name='peak_intensity',
            field=models.TextField(blank=True, help_text='A list of comma separated values, e.g., "1,2,3"'),
        ),
        migrations.AlterField(
            model_name='collapsedspectra',
            name='peak_mass',
            field=models.TextField(blank=True, help_text='A list of comma separated values, e.g., "1,2,3"'),
        ),
        migrations.AlterField(
            model_name='collapsedspectra',
            name='peak_snr',
            field=models.TextField(blank=True, help_text='A list of comma separated values, e.g., "1,2,3"'),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='peak_intensity',
            field=models.TextField(blank=True, help_text='A list of comma separated values, e.g., "1,2,3"'),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='peak_mass',
            field=models.TextField(blank=True, help_text='A list of comma separated values, e.g., "1,2,3"'),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='peak_snr',
            field=models.TextField(blank=True, help_text='A list of comma separated values, e.g., "1,2,3"'),
        ),
    ]
