# Generated by Django 2.2.13 on 2021-01-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0057_auto_20210111_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectra',
            name='ignore',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collapsedspectra',
            name='privacy_level',
            field=models.CharField(blank=True, choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='collapsedspectra',
            name='spectrum_intensity_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='collapsedspectra',
            name='spectrum_mass_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='searchspectra',
            name='privacy_level',
            field=models.CharField(blank=True, choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='searchspectra',
            name='spectrum_intensity_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='searchspectra',
            name='spectrum_mass_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='acquisition_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='acquisition_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='acquisition_mode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='acquisition_operator_mode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='cId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='data_system',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='data_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='digitizer_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='flex_control_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='inlet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='instrument',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='instrument_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='ionization_mode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='patch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='picture',
            field=models.ImageField(blank=True, upload_to='spectra_images'),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='privacy_level',
            field=models.CharField(blank=True, choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='spectrometer_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='spectrum_intensity_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='spectrum_mass_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='spectrum_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='spot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='target_id_string',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='target_serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='target_type_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='tof_mode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
