# Generated by Django 2.2.13 on 2021-01-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0058_auto_20210112_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectra',
            name='laser_repetition',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='target_count',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
    ]
