# Generated by Django 2.2.13 on 2021-01-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0060_auto_20210113_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectra',
            name='acquisition_date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
