# Generated by Django 2.2.13 on 2021-01-14 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0060_auto_20210113_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cClass',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cGenus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cKingdom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cOrder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cPhylum',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cSpecies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cultivation_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cultivation_temp_celsius',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cultivation_time_days',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='dna_16s',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='dsm_cultivation_media',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='genbank_accession',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='maldi_matrix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='ncbi_taxid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='pi_firstname_lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='pi_orcid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='strain_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='user_firstname_lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='user_orcid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spectra',
            name='acquisition_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xml',
            name='analyzer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xml',
            name='detector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xml',
            name='ionization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
