# Generated by Django 2.2.13 on 2021-01-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0061_auto_20210114_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xml',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xml',
            name='xml_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
