# Generated by Django 3.1 on 2021-02-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0062_auto_20210114_0017'),
        ('chat', '0061_auto_20210113_2338'),
    ]

    operations = [
    ]
