# Generated by Django 3.1 on 2021-02-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0065_auto_20210209_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='spectra',
            field=models.ManyToManyField(blank=True, null=True, to='chat.Spectra'),
        ),
    ]
