# Generated by Django 3.1 on 2021-02-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0070_auto_20210210_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskstatus',
            name='user_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.usertask'),
        ),
    ]
