# Generated by Django 3.1 on 2021-05-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210326_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lab_name',
            new_name='lab',
        ),
    ]
