# Generated by Django 3.1 on 2021-05-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210512_0245'),
        ('spectra', '0003_auto_20210505_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collapsedcosinescore',
            name='spectra1',
        ),
        migrations.RemoveField(
            model_name='collapsedcosinescore',
            name='spectra2',
        ),
        migrations.AddField(
            model_name='collapsedcosinescore',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.library'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collapsedcosinescore',
            name='scores',
            field=models.TextField(default=(1, 1, 1, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collapsedcosinescore',
            name='spectra',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='spectra.collapsedspectra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collapsedcosinescore',
            name='spectra_ids',
            field=models.TextField(default=(6, 7, 8, 9, 10)),
            preserve_default=False,
        ),
    ]
