# Generated by Django 3.1 on 2021-05-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0004_auto_20210513_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collapsedcosinescore',
            name='score',
        ),
    ]
