# Generated by Django 3.1 on 2021-05-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0005_remove_collapsedcosinescore_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collapsedspectra',
            old_name='lab_name',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='searchspectra',
            old_name='lab_name',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='spectra',
            old_name='lab_name',
            new_name='lab',
        ),
    ]
