# Generated by Django 3.1 on 2021-06-09 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0006_auto_20210517_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinnedPeaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_mass', models.TextField(blank=True)),
                ('peak_intensity', models.TextField(blank=True)),
                ('peak_snr', models.TextField(blank=True)),
                ('spectra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectra.collapsedspectra')),
            ],
        ),
        migrations.AddField(
            model_name='collapsedcosinescore',
            name='binned_peaks',
            field=models.ManyToManyField(to='spectra.BinnedPeaks'),
        ),
    ]
