# Generated by Django 3.1 on 2021-06-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0008_auto_20210611_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collapsedspectra',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='searchspectra',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='spectra',
            name='lab',
        ),
    ]
