# Generated by Django 3.1 on 2021-06-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20210630_2316'),
        ('spectra', '0009_auto_20210630_2312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collapsedspectra',
            unique_together={('strain_id', 'library')},
        ),
        migrations.AlterUniqueTogether(
            name='searchspectra',
            unique_together={('strain_id', 'library')},
        ),
    ]
