# Generated by Django 3.1 on 2021-06-30 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20210630_2316'),
        ('spectra', '0010_auto_20210630_2321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collapsedspectra',
            unique_together={('xml_hash', 'library')},
        ),
        migrations.AlterUniqueTogether(
            name='searchspectra',
            unique_together={('xml_hash', 'library')},
        ),
    ]
