# Generated by Django 3.1 on 2021-07-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0014_auto_20210630_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collapsedspectra',
            name='privacy_level',
        ),
        migrations.RemoveField(
            model_name='searchspectra',
            name='privacy_level',
        ),
        migrations.RemoveField(
            model_name='spectra',
            name='privacy_level',
        ),
    ]
