# Generated by Django 3.1 on 2021-07-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0015_auto_20210709_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collapsedcosinescore',
            old_name='scores',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='collapsedcosinescore',
            name='spectra_ids',
        ),
    ]
