# Generated by Django 3.1 on 2021-07-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0016_auto_20210711_2239'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collapsedcosinescore',
            index=models.Index(fields=['spectra', 'library'], name='spectra_col_spectra_f745b1_idx'),
        ),
    ]
