# Generated by Django 3.1 on 2021-07-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0017_auto_20210712_2234'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collapsedcosinescore',
            name='spectra_col_spectra_f745b1_idx',
        ),
    ]
