# Generated by Django 3.1 on 2021-07-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20210711_1542'),
        ('spectra', '0019_auto_20210713_2221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collapsedspectra',
            unique_together={('spectrum_mass_hash', 'spectrum_intensity_hash', 'library')},
        ),
        migrations.AlterUniqueTogether(
            name='searchspectra',
            unique_together={('spectrum_mass_hash', 'spectrum_intensity_hash', 'library')},
        ),
    ]
