# Generated by Django 3.1 on 2021-07-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20210711_1542'),
        ('spectra', '0020_auto_20210713_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrariesCosineScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('libraries', models.ManyToManyField(to='chat.Library')),
            ],
        ),
    ]
